// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: QuantityManage.proto

// Protobuf Java Version: 3.25.1
package inventory;

public final class inventoryImpl {
  private inventoryImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_inventory_ProductQuantityRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_inventory_ProductQuantityRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_inventory_ProductQuantityResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_inventory_ProductQuantityResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_inventory_RestockRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_inventory_RestockRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_inventory_RestockResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_inventory_RestockResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_inventory_ProductQuantityMonitorRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_inventory_ProductQuantityMonitorRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_inventory_ProductQuantityMonitorResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_inventory_ProductQuantityMonitorResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024QuantityManage.proto\022\tinventory\"+\n\026Pro" +
      "ductQuantityRequest\022\021\n\tproductNo\030\001 \001(\t\"L" +
      "\n\027ProductQuantityResponse\022\014\n\004date\030\001 \001(\t\022" +
      "\021\n\tproductNo\030\002 \001(\t\022\020\n\010quantity\030\003 \001(\005\"5\n\016" +
      "RestockRequest\022\021\n\tproductNo\030\001 \001(\t\022\020\n\010qua" +
      "ntity\030\002 \001(\005\"!\n\017RestockResponse\022\016\n\006status" +
      "\030\001 \001(\t\"2\n\035ProductQuantityMonitorRequest\022" +
      "\021\n\tproductNo\030\001 \001(\t\"c\n\036ProductQuantityMon" +
      "itorResponse\022\021\n\tproductNo\030\001 \001(\t\022\014\n\004date\030" +
      "\002 \001(\t\022\020\n\010quantity\030\003 \001(\005\022\016\n\006status\030\004 \001(\t2" +
      "\265\002\n\020InventoryService\022_\n\022GetProductQuanti" +
      "ty\022!.inventory.ProductQuantityRequest\032\"." +
      "inventory.ProductQuantityResponse\"\0000\001\022K\n" +
      "\016RestockProduct\022\031.inventory.RestockReque" +
      "st\032\032.inventory.RestockResponse\"\000(\001\022s\n\026Mo" +
      "nitorProductQuantity\022(.inventory.Product" +
      "QuantityMonitorRequest\032).inventory.Produ" +
      "ctQuantityMonitorResponse\"\000(\0010\001B\034\n\tinven" +
      "toryB\rinventoryImplP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_inventory_ProductQuantityRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_inventory_ProductQuantityRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_inventory_ProductQuantityRequest_descriptor,
        new java.lang.String[] { "ProductNo", });
    internal_static_inventory_ProductQuantityResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_inventory_ProductQuantityResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_inventory_ProductQuantityResponse_descriptor,
        new java.lang.String[] { "Date", "ProductNo", "Quantity", });
    internal_static_inventory_RestockRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_inventory_RestockRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_inventory_RestockRequest_descriptor,
        new java.lang.String[] { "ProductNo", "Quantity", });
    internal_static_inventory_RestockResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_inventory_RestockResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_inventory_RestockResponse_descriptor,
        new java.lang.String[] { "Status", });
    internal_static_inventory_ProductQuantityMonitorRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_inventory_ProductQuantityMonitorRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_inventory_ProductQuantityMonitorRequest_descriptor,
        new java.lang.String[] { "ProductNo", });
    internal_static_inventory_ProductQuantityMonitorResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_inventory_ProductQuantityMonitorResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_inventory_ProductQuantityMonitorResponse_descriptor,
        new java.lang.String[] { "ProductNo", "Date", "Quantity", "Status", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
