// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: QuantityManage.proto

// Protobuf Java Version: 3.25.1
package inventory;

public interface ProductQuantityMonitorRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:inventory.ProductQuantityMonitorRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string productNo = 1;</code>
   * @return The productNo.
   */
  java.lang.String getProductNo();
  /**
   * <code>string productNo = 1;</code>
   * @return The bytes for productNo.
   */
  com.google.protobuf.ByteString
      getProductNoBytes();
}
