// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: QuantityManage.proto

// Protobuf Java Version: 3.25.1
package inventory;

public interface ProductQuantityMonitorResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:inventory.ProductQuantityMonitorResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string productNo = 1;</code>
   * @return The productNo.
   */
  java.lang.String getProductNo();
  /**
   * <code>string productNo = 1;</code>
   * @return The bytes for productNo.
   */
  com.google.protobuf.ByteString
      getProductNoBytes();

  /**
   * <code>string date = 2;</code>
   * @return The date.
   */
  java.lang.String getDate();
  /**
   * <code>string date = 2;</code>
   * @return The bytes for date.
   */
  com.google.protobuf.ByteString
      getDateBytes();

  /**
   * <code>int32 quantity = 3;</code>
   * @return The quantity.
   */
  int getQuantity();

  /**
   * <code>string status = 4;</code>
   * @return The status.
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 4;</code>
   * @return The bytes for status.
   */
  com.google.protobuf.ByteString
      getStatusBytes();
}
