// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ExpirationManage.proto

// Protobuf Java Version: 3.25.1
package expiry;

public final class expiryImpl {
  private expiryImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_expiry_ProductExpiryRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_expiry_ProductExpiryRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_expiry_ProductExpiryResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_expiry_ProductExpiryResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_expiry_ProductExpiryMonitorRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_expiry_ProductExpiryMonitorRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_expiry_ProductExpiryMonitorResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_expiry_ProductExpiryMonitorResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026ExpirationManage.proto\022\006expiry\"+\n\024Prod" +
      "uctExpiryRequest\022\023\n\013productType\030\001 \001(\t\"@\n" +
      "\025ProductExpiryResponse\022\023\n\013productType\030\001 " +
      "\001(\t\022\022\n\nbestBefore\030\002 \001(\t\"2\n\033ProductExpiry" +
      "MonitorRequest\022\023\n\013productType\030\001 \001(\t\"e\n\034P" +
      "roductExpiryMonitorResponse\022\023\n\013productTy" +
      "pe\030\001 \001(\t\022\022\n\nbestBefore\030\002 \001(\t\022\014\n\004date\030\003 \001" +
      "(\t\022\016\n\006status\030\004 \001(\t2\313\001\n\rExpiryService\022Q\n\020" +
      "GetProductExpiry\022\034.expiry.ProductExpiryR" +
      "equest\032\035.expiry.ProductExpiryResponse\"\000\022" +
      "g\n\024MonitorProductExpiry\022#.expiry.Product" +
      "ExpiryMonitorRequest\032$.expiry.ProductExp" +
      "iryMonitorResponse\"\000(\0010\001B\026\n\006expiryB\nexpi" +
      "ryImplP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_expiry_ProductExpiryRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_expiry_ProductExpiryRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_expiry_ProductExpiryRequest_descriptor,
        new java.lang.String[] { "ProductType", });
    internal_static_expiry_ProductExpiryResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_expiry_ProductExpiryResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_expiry_ProductExpiryResponse_descriptor,
        new java.lang.String[] { "ProductType", "BestBefore", });
    internal_static_expiry_ProductExpiryMonitorRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_expiry_ProductExpiryMonitorRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_expiry_ProductExpiryMonitorRequest_descriptor,
        new java.lang.String[] { "ProductType", });
    internal_static_expiry_ProductExpiryMonitorResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_expiry_ProductExpiryMonitorResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_expiry_ProductExpiryMonitorResponse_descriptor,
        new java.lang.String[] { "ProductType", "BestBefore", "Date", "Status", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
