// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ExpirationManage.proto

// Protobuf Java Version: 3.25.1
package expiry;

public interface ProductExpiryResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:expiry.ProductExpiryResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string productType = 1;</code>
   * @return The productType.
   */
  java.lang.String getProductType();
  /**
   * <code>string productType = 1;</code>
   * @return The bytes for productType.
   */
  com.google.protobuf.ByteString
      getProductTypeBytes();

  /**
   * <code>string bestBefore = 2;</code>
   * @return The bestBefore.
   */
  java.lang.String getBestBefore();
  /**
   * <code>string bestBefore = 2;</code>
   * @return The bytes for bestBefore.
   */
  com.google.protobuf.ByteString
      getBestBeforeBytes();
}
