// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ExpirationManage.proto

// Protobuf Java Version: 3.25.1
package expiry;

public interface ProductExpiryMonitorResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:expiry.ProductExpiryMonitorResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string productType = 1;</code>
   * @return The productType.
   */
  java.lang.String getProductType();
  /**
   * <code>string productType = 1;</code>
   * @return The bytes for productType.
   */
  com.google.protobuf.ByteString
      getProductTypeBytes();

  /**
   * <code>string bestBefore = 2;</code>
   * @return The bestBefore.
   */
  java.lang.String getBestBefore();
  /**
   * <code>string bestBefore = 2;</code>
   * @return The bytes for bestBefore.
   */
  com.google.protobuf.ByteString
      getBestBeforeBytes();

  /**
   * <code>string date = 3;</code>
   * @return The date.
   */
  java.lang.String getDate();
  /**
   * <code>string date = 3;</code>
   * @return The bytes for date.
   */
  com.google.protobuf.ByteString
      getDateBytes();

  /**
   * <code>string status = 4;</code>
   * @return The status.
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 4;</code>
   * @return The bytes for status.
   */
  com.google.protobuf.ByteString
      getStatusBytes();
}
