// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ExpirationManage.proto

// Protobuf Java Version: 3.25.1
package expiry;

public interface ProductExpiryMonitorRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:expiry.ProductExpiryMonitorRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string productType = 1;</code>
   * @return The productType.
   */
  java.lang.String getProductType();
  /**
   * <code>string productType = 1;</code>
   * @return The bytes for productType.
   */
  com.google.protobuf.ByteString
      getProductTypeBytes();
}
