// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TemperatureService.proto

package com.ncirl.streaming.temperatureservice;

public interface TemperatureInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ncirl.streaming.TemperatureInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string time = 1;</code>
   */
  java.lang.String getTime();
  /**
   * <code>string time = 1;</code>
   */
  com.google.protobuf.ByteString
      getTimeBytes();

  /**
   * <code>string temp = 2;</code>
   */
  java.lang.String getTemp();
  /**
   * <code>string temp = 2;</code>
   */
  com.google.protobuf.ByteString
      getTempBytes();
}
