// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TempManage.proto

// Protobuf Java Version: 3.25.1
package temperature;

public interface FridgeControlRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:temperature.FridgeControlRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.temperature.FridgeControlRequest.Action action = 1;</code>
   * @return The enum numeric value on the wire for action.
   */
  int getActionValue();
  /**
   * <code>.temperature.FridgeControlRequest.Action action = 1;</code>
   * @return The action.
   */
  temperature.FridgeControlRequest.Action getAction();
}
