// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TempManage.proto

// Protobuf Java Version: 3.25.1
package temperature;

public interface TemperatureMonitorResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:temperature.TemperatureMonitorResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string status = 1;</code>
   * @return The status.
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 1;</code>
   * @return The bytes for status.
   */
  com.google.protobuf.ByteString
      getStatusBytes();
}
