// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StoreService.proto

package com.ncirl.streaming.storeservice;

public interface ProductInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ncirl.streaming.ProductInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string productNo = 1;</code>
   */
  java.lang.String getProductNo();
  /**
   * <code>string productNo = 1;</code>
   */
  com.google.protobuf.ByteString
      getProductNoBytes();

  /**
   * <code>int32 count = 2;</code>
   */
  int getCount();
}
