// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StoreService.proto

package com.ncirl.streaming.storeservice;

public interface ProductInfosOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ncirl.streaming.ProductInfos)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.ncirl.streaming.ProductInfo products = 1;</code>
   */
  java.util.List<com.ncirl.streaming.storeservice.ProductInfo> 
      getProductsList();
  /**
   * <code>repeated .com.ncirl.streaming.ProductInfo products = 1;</code>
   */
  com.ncirl.streaming.storeservice.ProductInfo getProducts(int index);
  /**
   * <code>repeated .com.ncirl.streaming.ProductInfo products = 1;</code>
   */
  int getProductsCount();
  /**
   * <code>repeated .com.ncirl.streaming.ProductInfo products = 1;</code>
   */
  java.util.List<? extends com.ncirl.streaming.storeservice.ProductInfoOrBuilder> 
      getProductsOrBuilderList();
  /**
   * <code>repeated .com.ncirl.streaming.ProductInfo products = 1;</code>
   */
  com.ncirl.streaming.storeservice.ProductInfoOrBuilder getProductsOrBuilder(
      int index);
}
