// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StoreService.proto

package com.ncirl.streaming.storeservice;

public final class StoreServiceProto {
  private StoreServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ncirl_streaming_ProductInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ncirl_streaming_ProductInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ncirl_streaming_ProductInfos_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ncirl_streaming_ProductInfos_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022StoreService.proto\022\023com.ncirl.streamin" +
      "g\"/\n\013ProductInfo\022\021\n\tproductNo\030\001 \001(\t\022\r\n\005c" +
      "ount\030\002 \001(\005\"B\n\014ProductInfos\0222\n\010products\030\001" +
      " \003(\0132 .com.ncirl.streaming.ProductInfo2\355" +
      "\002\n\014StoreService\022V\n\017getProductsInfo\022 .com" +
      ".ncirl.streaming.ProductInfo\032!.com.ncirl" +
      ".streaming.ProductInfos\022Z\n\022getAllProduct" +
      "sInfo\022 .com.ncirl.streaming.ProductInfo\032" +
      " .com.ncirl.streaming.ProductInfo0\001\022X\n\021u" +
      "pdateProductInfo\022 .com.ncirl.streaming.P" +
      "roductInfo\032!.com.ncirl.streaming.Product" +
      "Infos\022O\n\006upload\022 .com.ncirl.streaming.Pr" +
      "oductInfo\032!.com.ncirl.streaming.ProductI" +
      "nfos(\001B7\n com.ncirl.streaming.storeservi" +
      "ceB\021StoreServiceProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_ncirl_streaming_ProductInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_ncirl_streaming_ProductInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ncirl_streaming_ProductInfo_descriptor,
        new java.lang.String[] { "ProductNo", "Count", });
    internal_static_com_ncirl_streaming_ProductInfos_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_ncirl_streaming_ProductInfos_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ncirl_streaming_ProductInfos_descriptor,
        new java.lang.String[] { "Products", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
