// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HumidityService.proto

package com.ncirl.streaming.humidityservice;

public interface HumidityInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ncirl.streaming.HumidityInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string time = 1;</code>
   */
  java.lang.String getTime();
  /**
   * <code>string time = 1;</code>
   */
  com.google.protobuf.ByteString
      getTimeBytes();

  /**
   * <code>string humidity = 2;</code>
   */
  java.lang.String getHumidity();
  /**
   * <code>string humidity = 2;</code>
   */
  com.google.protobuf.ByteString
      getHumidityBytes();
}
